### ISSUE TITLE
regex-syntax is probably unnecessary

### ISSUE THREAD

**Issue by BurntSushi** [dono-app/dono-crate#2]
Apologies if I've scanned too quickly and misunderstood your usage scenario, but the `regex` crate exports a [`quote`](https://doc.rust-lang.org/regex/regex/fn.quote.html) function that you should be able to use for escapes. You shouldn't need to also bring in `regex-syntax`. :-)

**Comment by Stankec** [comment]
My pardons. Somehow I didn't get notified when you opened this issue (seems like I forgot to watch my own repository). Yes. You are correct. I'll change it by the end of the day. Or if you want to help out I can tag this with hacktober, so you get a cool T-Shirt for doing it :)

**Comment by Stankec** [comment]
Is this what you had in mind? #4

**Comment by BurntSushi** [comment]
Looks good to me!

**Comment by Stankec** [comment]
Ok, closing this issue then. Tnx :)
