### ISSUE TITLE
Change lables store location

### ISSUE THREAD

**Issue by Stankec** [dono-app/dono-crate#6]
On macOS the lables are read from `~/Documents/.labels` this has changed in the whitepaper and this library should reflect that. The new store location is `~/.labels`

**Comment by kc1212** [comment]
Would that be just updating the the `store_location` function and the corresponding test? I suspect the the `os_type` crate can also be removed.

**Comment by Stankec** [comment]
That's exactly what needs to be done.

**Comment by Stankec** [comment]
![tank_you_by_victorpaiam-d4h6q6d](https://cloud.githubusercontent.com/assets/1655218/19212859/ed7be18e-8d5b-11e6-913f-dd4b98f64ad0.jpg)

Thank you for the contribution 😃
